server:
  port: 8087

spring:
  application:
    name: ms-postventa
  datasource:
    url: jdbc:mariadb://localhost:3306/db_postventa?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

# implementacion de swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# 2. La dirección del Directorio Telefónico (Eureka Server)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/